name: health-hei-admin

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "*/5 6-15 * * 1-5" # Exécuter toutes les 5 minutes de 8h à 17h (UTC+3) pendant les jours ouvrables

env:
  HEI_ADMIN_NOTIFICATION_URL: ${{ secrets.HEI_ADMIN_NOTIFICATION_URL }}

  CYPRESS_HEI_ADMIN_URL: ${{ secrets.CYPRESS_HEI_ADMIN_URL }}
  CYPRESS_HEI_ADMIN_USERNAME: ${{ secrets.CYPRESS_HEI_ADMIN_USERNAME }}
  CYPRESS_HEI_ADMIN_PASSWORD: ${{ secrets.CYPRESS_HEI_ADMIN_PASSWORD }}

jobs:
  health-check:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run hei-admin test
        id: cypress-tests
        uses: cypress-io/github-action@v6
        with:
          spec: "./cypress/e2e/hei-admin/*.js"

      - name: Send status to Instatus
        if: ${{ always() && github.event_name == 'schedule' }}
        run: |
          trigger=$(if [ '${{ job.status }}' == 'failure' ]; then echo 'down'; else echo 'up'; fi)
          echo "Trigger status is: $trigger"
          curl -X POST "${{ secrets.HEI_ADMIN_NOTIFICATION_URL }}" \
            -H "Content-Type: application/json" \
            -d "{\"trigger\": \"$trigger\"}"