name: health-mail

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 6-15 * * 1-5" # Exécuter toutes les 5 minutes de 8h à 17h (UTC+3) pendant les jours ouvrables

env:
  CYPRESS_MAIL_URL: ${{ secrets.CYPRESS_MAIL_URL }}

  CYPRESS_MAIL_USERNAME: ${{ secrets.CYPRESS_MAIL_USERNAME }}
  CYPRESS_MAIL_PASSWORD: ${{ secrets.CYPRESS_MAIL_PASSWORD }}

  CYPRESS_MAIL_ADMIN_USERNAME: ${{ secrets.CYPRESS_MAIL_ADMIN_USERNAME }}
  CYPRESS_MAIL_ADMIN_PASSWORD: ${{ secrets.CYPRESS_MAIL_ADMIN_PASSWORD }}

jobs:
  auth-check:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run mail tests
        uses: cypress-io/github-action@v6
        with:
          spec: "./cypress/e2e/mail/auth-*.js"

  send-mail:
    needs: auth-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Send mail using Cypress
        uses: cypress-io/github-action@v6
        with:
          spec: "./cypress/e2e/mail/send-mail.cy.js"
        env:
          CYPRESS_MAIL_URL: ${{ secrets.CYPRESS_MAIL_URL }}
          CYPRESS_MAIL_USERNAME: ${{ secrets.CYPRESS_MAIL_USERNAME }}
          CYPRESS_MAIL_PASSWORD: ${{ secrets.CYPRESS_MAIL_PASSWORD }}
          CYPRESS_MAIL_RECEIVER_USERNAME: ${{ secrets.CYPRESS_MAIL_RECEIVER_USERNAME }}

  check-error-mail:
    needs: send-mail
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Check for error mail
        uses: cypress-io/github-action@v6
        with:
          spec: "./cypress/e2e/mail/check-error-mail.cy.js"

      - name: Send status to Instatus
        if: ${{ always() && github.event_name == 'schedule' }}
        run: |
          trigger=$(if [ '${{ job.status }}' == 'failure' ]; then echo 'down'; else echo 'up'; fi)
          echo "Trigger status is: $trigger"
          curl -X POST "${{ vars.MAIL_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d "{\"trigger\": \"$trigger\"}"
